### PR TITLE
Spanification

### PR DESCRIPTION
**Pull request by Happypig375**
```cs
            var str = new string(System.Linq.Enumerable.ToArray(
                System.Linq.Enumerable.Select(System.Linq.Enumerable.Range(0, 256), c => (char)c)));
            var breaker = new Typography.TextBreak.CustomBreaker();
            var list = new List<Typography.TextBreak.BreakAtInfo>();
            for (int i = 0; i < 10000; i++) {
#if Before
                breaker.BreakWords(str);
                breaker.CopyBreakResults(list);
#else
                breaker.BreakWords(str, list);
#endif
            }
```

Benchmark using BenchMarkDotNet:

Before:
image

After:
image

### CODE REVIEW

**Comment by Happypig375** [comment]
Note: Avoid opening the System.Runtime.CompilerServices.Unsafe project or the System.Memory project unless you can cope with an Error List full of nonexistent errors.

**Comment by prepare** [comment]
@Happypig375 , 

Can you compare both in release mode ?

**Comment by Happypig375** [comment]
BenchMarkDotNet already requires release mode to function.

**Comment by Happypig375** [comment]
Re-run without debugger:

BenchMarkDotNet info: Runtime=.NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3163.0

Before:

image
After:
image

**Comment by Happypig375** [comment]
Well, if you want a reason to support such a drastic change, requiring a backport of a .NET Core library to the Framework, is that [the .NET Framework is getting sunsetted.](https://www.reddit.com/r/csharp/comments/9hpjob/the_net_framework_is_done/?utm_source=reddit-android) It is not important to maintain .NET Framework support anymore. As such, adopting new .NET Core features should not be blocked by the Framework.

The speed boost I measured is probably the result of changing a few types to `ref struct`s, which won't make sense when not using those Spanny stuff.

**Comment by zwcloud** [comment]
> It is not important to maintain .NET Framework support anymore. As such, adopting new .NET Core features should not be blocked by the Framework.

+1

**Comment by Happypig375** [comment]
Moreover, with the improvements of Span on newer runtimes, it is actually faster than areays because there will be no array covariance checks.

So please, if you have scrolled through every change and they are looking good, then please merge. I would like to get rid of all the substrings in CSharpMath.

**Comment by prepare** [comment]
Hello! ,Thank you for this PR

---

I'm ok with new's C# and .Net features (eg. span).

A performance  problem is one of my top concerns.

But _at this time_ , I've  some limitations that =>

1. Other repos (eg. HtmlRenderer, PixelFarm) may not ready for this.
2. Other users that still can't update to newer .net => are not ready
3. "Auto-Gen" tools are not this.
4. ... 

So, I need to look back and see 

_What make char[] slower and Can I improve the code?_

The performance may be improved with

1. unsafe char* , 
2. native memory
3. not convert string to char[] 
4. not add  _StopAt_ result into a List and copy it again.

etc.

---

So please give me a time, 

If above can't improve the performance =>

then it would be the time that I must talk to

other repo / users to update it.



:)

---

**Comment by Happypig375** [comment]
Re: Limitations

1. Then please just use Spans everywhere. They are super fast on newer runtimes and should be used.

2. I literally backported System.Memory to .NET Framework 2.0. It constitutes a sizable chunk of this PR. Just reference that project and everything will be fine. The performance improvement is still there. The above benchmarks are measuring my .NET Framework 2.0 backport running on 4.7.2.

3. Which Auto-Gen tools? You've never shared any info on this before.

4. Any more arguments are welcome :)

Re: Performance improvements
1, 2. Currently requiring arrays forbid users from using unmanaged memory or stack memory and using TextBreak on it. It is not juat about Typography/PixelFarm/HtmlRenderer's own performance, it is also about the ways the user can use them.

3, 4. I did those in this PR. You can see the places that I employed this methodology in the diff.

---

The above methods _CAN_ improve the speed of TextBreak. The benchmarks indicate so, at least.

----

Any responses are welcome ;)

**Comment by prepare** [comment]
I created a new brach _dev2_ and 
merge this into it (https://github.com/LayoutFarm/Typography/commit/ac973db66d4f6f6d90751c70170e8d92f7353122)

**Comment by prepare** [comment]
Before merging all , I will update both branch _dev_ and _dev2_

**Comment by prepare** [comment]
What is "Auto-Gen" Tools.



They are simple .net projects 
that merge all sub-projects (at source level) into 1 project.

so we can get _one_ asm (eg. PixelFarm.HtmlRenderer.One )


They are here https://github.com/PaintLab/PixelFarm/tree/dev/src/Tools

**Pull request closed without merging**
