### PR TITLE
Allow GlyphLayout.Layout to be used with glyph indices when the original string is not available

### PR DESCRIPTION
**Pull request by Happypig375**

### CODE REVIEW

**Comment by prepare** [comment]
@Happypig375 ,

You have 
1) a pre-built glyph-indices **with** related code-points 
or
2)  just a pre-built glyph-indices **without** related code-points?

---

please provide an example (or link)  to the usage-situation

**Comment by Happypig375** [comment]
Oooh, I overlooked `_gsub.DoSubstitution(_inputGlyphs);` which may use codepoints. Sorry.

-------------

My situation is that I do have the related codepoints, but I have to convert them to glyphs then break them up according to their typefaces to supply the GlyphLayout with the correct one; then call LayoutAndMeasureString (the new overload is not included in this PR as this has to be merged first)

-------------

Alternatively, if I can get the equivalent height as LayoutAndMeasureString from some kind of new method on Glyph, that would also be great. (I need the extra height from LayoutAndMeasureString that is not included in Glyph.Bounds.)

**Comment by prepare** [comment]
@Happypig375 , 

You start layout with code-point list =>

something like this is suite?

    public void Layout( uint[] codepoints,  int startAt, int len);

**Comment by Happypig375** [comment]
Yea, maybe start with something like that.

**Comment by Happypig375** [comment]
A corresponding overload of `LayoutAndMeasureString` would also call this to layout;
And StringUtils.GetCodepoints would return uint.

Let me try this.

**Comment by Happypig375** [comment]
Merge into #140

**Comment by prepare** [comment]
please visit this https://github.com/LayoutFarm/Typography/commit/65178af800e5c4dd705504be65761b1e957c600c

**Pull request closed without merging**
