### PR TITLE
New #139

### PR DESCRIPTION
**Pull request by Happypig375**
I have no time for new LayoutAndMeasureString overload, please implement

### CODE REVIEW

**Comment by prepare** [comment]
new member=>
GlyphLayout.Layout(IList<int>) and its overload 
 please check this https://github.com/LayoutFarm/Typography/commit/65178af800e5c4dd705504be65761b1e957c600c

**Comment by prepare** [comment]
new member=>
GlyphLayout.Layout(IList) and its overload
please check this 65178af

see the merge here https://github.com/LayoutFarm/Typography/commit/12dfde5f10fea98504bffb3fdc46d6b1db20f0b2

**Comment by prepare** [comment]
Not sure if it is fit for you. 

Welcome all PR(s)

**Comment by Happypig375** [comment]
@prepare
This also contains lots of int -> uint type changes. They should be useful.

**Comment by prepare** [comment]
From .net Char type



     // Summary:
        //     Converts the value of a UTF-16 encoded surrogate pair into a Unicode code point.
        //
        // Parameters:
        //   highSurrogate:
        //     A high surrogate code unit (that is, a code unit ranging from U+D800 through
        //     U+DBFF).
        //
        //   lowSurrogate:
        //     A low surrogate code unit (that is, a code unit ranging from U+DC00 through U+DFFF).
        //
        // Returns:
        //     The 21-bit Unicode code point represented by the highSurrogate and lowSurrogate
        //     parameters.
        //
        // Exceptions:
        //   T:System.ArgumentOutOfRangeException:
        //     highSurrogate is not in the range U+D800 through U+DBFF, or lowSurrogate is not
        //     in the range U+DC00 through U+DFFF.
        public static int ConvertToUtf32(Char highSurrogate, Char lowSurrogate);


---
so it should be int for codepoints

**Comment by prepare** [comment]
from  https://en.wikipedia.org/wiki/Code_point

....  Unicode comprises 1,114,112 code points in the range 0hex to 10FFFFhex.

---

It should be ok with int.

**Comment by Happypig375** [comment]
The reason for ConvertToUtf32 returning an int, not an uint is because of CLS compliance. None of that matters these days. Besides, using uint will prevent negative values and stuff like that.

**Pull request closed without merging**
