### PR TITLE
Add a OpenGLES-based demo project for Android.

### PR DESCRIPTION
**Pull request by zwcloud**
Also add [a new `Read` function to `IGlyphReaderExtensions`](https://github.com/LayoutFarm/Typography/compare/master...zwcloud:android_demo?expand=1#diff-4574b230f99cb73314884b18dbf0cd8aR287) so the offset of the glyph can be applied while the glyph geometry is being read.

The demo also introduces a new way to render glyphs. I will write an article about it later.

### CODE REVIEW

**Comment by prepare** [comment]
Thank you 👍 

Give me a time to test it :)

**Comment by prepare** [comment]
I'm updating the code to latest main branch
---
@zwcloud ,

I concern about license of the code.
I can't combine any copy-left code.

1. Do you mind if I use MIT license for your code ?

2. Is code in CSharpGLES namespace yours?,
   if not, what is the original license?

**Comment by zwcloud** [comment]
There is no copy-left code. 

MIT is good for me.

CSharpGLES is taken from a modified version of [CSharpGL](https://github.com/bitzhuwei/CSharpGL) with no license.

**Comment by prepare** [comment]
Thank you

**Comment by prepare** [comment]
Build Pass, But I'm updating Android ...

**Comment by prepare** [comment]
Matrial Shader Compilation Error, I fixing it. 

I test it on Win7 64 bits, VS2017.

What is your dev environment?

---

android_01
_pic 1: This._

android_02
_pic 2: Call Stack Window_

android_03

pic 3: error here

**Comment by zwcloud** [comment]
I don't use a Android emulator. I tested the demo on my phone. The phone should support OpenGLES 3.0 to run the demo.

BTW, what's the content of the shader compilation log?

**Comment by zwcloud** [comment]
I recommend you install a [Visual Studio Emulator for Android][1]. It starts up much faster than the emulator provided by Google.

It can be installed via the VS2017 installer.
vs_installershell


[1]: https://www.visualstudio.com/vs/msft-android-emulator/

**Comment by zwcloud** [comment]
Oh, I got a mono runtime error when trying to run the demo in the eumlator. 😟

**Comment by zwcloud** [comment]
With the Android Emulator, I got the same exception as yours. But there are more error log before it.
The log indicates that the app failed to create the EGL context.

```
03-23 18:58:34.104	MyNexus5	Verbose	2247	Xamarin.OpenGL	OpenTK.Platform.Android.EglException: EglCreateContext == EGL10.EglNoContext failed with error 12293 (0x3005)
  at OpenTK.Platform.Android.AndroidGraphicsContext.Init (OpenTK.Graphics.GraphicsMode mode, OpenTK.Platform.IWindowInfo win, OpenTK.Graphics.IGraphicsContext sharedContext, System.Int32 major, OpenTK.Graphics.GraphicsContextFlags flags) [0x00143] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at OpenTK.Platform.Android.AndroidGraphicsContext..ctor (OpenTK.Graphics.GraphicsMode mode, OpenTK.Platform.IWindowInfo window, OpenTK.Graphics.IGraphicsContext sharedContext, OpenTK.Graphics.GLContextVersion glesVersion, OpenTK.Graphics.GraphicsContextFlags flags) [0x0000e] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at OpenTK.Platform.Android.AndroidGraphicsContext.CreateGraphicsContext (OpenTK.Graphics.GraphicsMode mode, OpenTK.Platform.IWindowInfo window, OpenTK.Graphics.IGraphicsContext sharedContext, OpenTK.Graphics.GLContextVersion glVersion, OpenTK.Graphics.GraphicsContextFlags flags) [0x00001] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at OpenTK.Platform.Android.AndroidGameView.CreateContext () [0x0001a] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at OpenTK.Platform.Android.AndroidGameView.MakeCurrent () [0x00012] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at OpenTK.Platform.Android.AndroidGameView.CreateFrameBuffer () [0x000a9] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at Xamarin.OpenGL.GLView1.CreateFrameBuffer () [0x0001a] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
03-23 18:58:38.777	MyNexus5	Info	2247	MonoDroid	CSharpGLES.ShaderCompilationException: Failed to compile shader with ID 0. Log: 
  at CSharpGLES.Shader.Create (OpenTK.Graphics.ES30.All shaderType, System.String source) [0x00071] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
  at CSharpGLES.ShaderProgram.Create (System.String vertexShaderSource, System.String fragmentShaderSource, System.Collections.Generic.Dictionary`2[TKey,TValue] attributeLocations) [0x00001] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
  at Xamarin.OpenGL.Material.CreateShaders () [0x00053] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
  at Xamarin.OpenGL.Material.Init () [0x00001] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
  at Xamarin.OpenGL.Material.InitMaterials () [0x00001] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
  at Xamarin.OpenGL.OpenGLESRenderer.Init () [0x00001] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
  at Xamarin.OpenGL.GLView1.OnLoad (System.EventArgs e) [0x0007a] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
  at OpenTK.Platform.Android.AndroidGameView.LoadInternal (System.EventArgs e) [0x00001] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at OpenTK.Platform.Android.AndroidGameView.SurfaceCreated (Android.Views.ISurfaceHolder holder) [0x0004c] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at Android.Views.ISurfaceHolderCallbackInvoker.n_SurfaceCreated_Landroid_view_SurfaceHolder_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_holder) [0x00011] in <630efd13234b47f3ac6be576f7ac3bd1>:0 
  at (wrapper dynamic-method) System.Object:fc61e06b-dffb-4cc2-88e5-aaaabf791bd7 (intptr,intptr,intptr)
03-23 18:57:34.596	MyNexus5	Warning	2215	monodroid	Using override path: /data/user/0/Xamarin.OpenGL.Xamarin.OpenGL/files/.__override__
03-23 18:58:34.166	MyNexus5	Verbose	2247	Xamarin.OpenGL	OpenTK.Platform.Android.EglException: EglCreateWindowSurface failed with error 12291 (0x3003)
  at OpenTK.Platform.Android.AndroidWindow.CreateSurface (Javax.Microedition.Khronos.Egl.EGLConfig config) [0x00072] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at OpenTK.Platform.Android.AndroidGameView.CreateFrameBuffer () [0x0009d] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at Xamarin.OpenGL.GLView1.CreateFrameBuffer () [0x0006b] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
03-23 18:57:46.553	MyNexus5	Verbose	2215	Xamarin.OpenGL	OpenTK.Platform.Android.EglException: EglCreateWindowSurface failed with error 12291 (0x3003)
  at OpenTK.Platform.Android.AndroidWindow.CreateSurface (Javax.Microedition.Khronos.Egl.EGLConfig config) [0x00072] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at OpenTK.Platform.Android.AndroidGameView.CreateFrameBuffer () [0x0009d] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at Xamarin.OpenGL.GLView1.CreateFrameBuffer () [0x0006b] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
03-23 18:58:12.431	MyNexus5	Warning	2247	monodroid	Using override path: /storage/emulated/0/Android/data/Xamarin.OpenGL.Xamarin.OpenGL/files/.__override__
03-23 18:58:12.434	MyNexus5	Warning	2247	monodroid	Trying to load sgen from: /storage/emulated/0/Android/data/Xamarin.OpenGL.Xamarin.OpenGL/files/.__override__/libmonosgen-2.0.so
03-23 18:57:48.194	MyNexus5	Info	2215	MonoDroid	UNHANDLED EXCEPTION:
03-23 18:57:45.746	MyNexus5	Verbose	2215	Xamarin.OpenGL	Loading with default settings
03-23 18:57:34.617	MyNexus5	Warning	2215	monodroid	Trying to load sgen from: /data/user/0/Xamarin.OpenGL.Xamarin.OpenGL/files/.__override__/libmonosgen-2.0.so
03-23 18:58:14.156	MyNexus5	Warning	2247	monodroid	Calling into managed runtime init
03-23 18:58:38.779	MyNexus5	Info	2247	MonoDroid	
03-23 18:57:46.485	MyNexus5	Verbose	2215	Xamarin.OpenGL	OpenTK.Platform.Android.EglException: EglCreateContext == EGL10.EglNoContext failed with error 12293 (0x3005)
  at OpenTK.Platform.Android.AndroidGraphicsContext.Init (OpenTK.Graphics.GraphicsMode mode, OpenTK.Platform.IWindowInfo win, OpenTK.Graphics.IGraphicsContext sharedContext, System.Int32 major, OpenTK.Graphics.GraphicsContextFlags flags) [0x00143] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at OpenTK.Platform.Android.AndroidGraphicsContext..ctor (OpenTK.Graphics.GraphicsMode mode, OpenTK.Platform.IWindowInfo window, OpenTK.Graphics.IGraphicsContext sharedContext, OpenTK.Graphics.GLContextVersion glesVersion, OpenTK.Graphics.GraphicsContextFlags flags) [0x0000e] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at OpenTK.Platform.Android.AndroidGraphicsContext.CreateGraphicsContext (OpenTK.Graphics.GraphicsMode mode, OpenTK.Platform.IWindowInfo window, OpenTK.Graphics.IGraphicsContext sharedContext, OpenTK.Graphics.GLContextVersion glVersion, OpenTK.Graphics.GraphicsContextFlags flags) [0x00001] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at OpenTK.Platform.Android.AndroidGameView.CreateContext () [0x0001a] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at OpenTK.Platform.Android.AndroidGameView.MakeCurrent () [0x00012] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at OpenTK.Platform.Android.AndroidGameView.CreateFrameBuffer () [0x000a9] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at Xamarin.OpenGL.GLView1.CreateFrameBuffer () [0x0001a] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
03-23 18:57:48.235	MyNexus5	Info	2215	MonoDroid	
03-23 18:57:34.635	MyNexus5	Warning	2215	monodroid	Trying to load sgen from: /data/user/0/Xamarin.OpenGL.Xamarin.OpenGL/files/.__override__/links/libmonosgen-2.0.so
03-23 18:58:32.242	MyNexus5	Verbose	2247	Xamarin.OpenGL	Loading with default settings
03-23 18:58:12.435	MyNexus5	Warning	2247	monodroid	Trying to load sgen from: /data/user/0/Xamarin.OpenGL.Xamarin.OpenGL/files/.__override__/links/libmonosgen-2.0.so
03-23 18:57:36.484	MyNexus5	Warning	2215	monodroid	Calling into managed runtime init
03-23 18:57:48.234	MyNexus5	Info	2215	MonoDroid	CSharpGLES.ShaderCompilationException: Failed to compile shader with ID 0. Log: 
  at CSharpGLES.Shader.Create (OpenTK.Graphics.ES30.All shaderType, System.String source) [0x00071] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
  at CSharpGLES.ShaderProgram.Create (System.String vertexShaderSource, System.String fragmentShaderSource, System.Collections.Generic.Dictionary`2[TKey,TValue] attributeLocations) [0x00001] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
  at Xamarin.OpenGL.Material.CreateShaders () [0x00053] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
  at Xamarin.OpenGL.Material.Init () [0x00001] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
  at Xamarin.OpenGL.Material.InitMaterials () [0x00001] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
  at Xamarin.OpenGL.OpenGLESRenderer.Init () [0x00001] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
  at Xamarin.OpenGL.GLView1.OnLoad (System.EventArgs e) [0x0007a] in <cb07309d3afc4d1f9ccdf0e198cff81e>:0 
  at OpenTK.Platform.Android.AndroidGameView.LoadInternal (System.EventArgs e) [0x00001] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at OpenTK.Platform.Android.AndroidGameView.SurfaceCreated (Android.Views.ISurfaceHolder holder) [0x0004c] in <70bcb72996b042398469c50bfc27bf5e>:0 
  at Android.Views.ISurfaceHolderCallbackInvoker.n_SurfaceCreated_Landroid_view_SurfaceHolder_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_holder) [0x00011] in <630efd13234b47f3ac6be576f7ac3bd1>:0 
  at (wrapper dynamic-method) System.Object:5e9c5bbf-8308-4943-a98e-01cf5d29f1fb (intptr,intptr,intptr)
03-23 18:58:12.434	MyNexus5	Warning	2247	monodroid	Trying to load sgen from: /data/app/Xamarin.OpenGL.Xamarin.OpenGL-1/lib/arm/libmonosgen-2.0.so
03-23 18:57:34.618	MyNexus5	Warning	2215	monodroid	Trying to load sgen from: /storage/emulated/0/Android/data/Xamarin.OpenGL.Xamarin.OpenGL/files/.__override__/libmonosgen-2.0.so
03-23 18:57:34.631	MyNexus5	Warning	2215	monodroid	Trying to load sgen from: /data/app/Xamarin.OpenGL.Xamarin.OpenGL-1/lib/arm/libmonosgen-2.0.so
03-23 18:58:12.426	MyNexus5	Warning	2247	monodroid	Using override path: /data/user/0/Xamarin.OpenGL.Xamarin.OpenGL/files/.__override__
03-23 18:57:46.487	MyNexus5	Verbose	2215	Xamarin.OpenGL	Loading with custom Android settings (low mode)
03-23 18:57:34.611	MyNexus5	Warning	2215	monodroid	Using override path: /storage/emulated/0/Android/data/Xamarin.OpenGL.Xamarin.OpenGL/files/.__override__
03-23 18:58:34.107	MyNexus5	Verbose	2247	Xamarin.OpenGL	Loading with custom Android settings (low mode)
03-23 18:58:38.689	MyNexus5	Info	2247	MonoDroid	UNHANDLED EXCEPTION:
03-23 18:58:12.433	MyNexus5	Warning	2247	monodroid	Trying to load sgen from: /data/user/0/Xamarin.OpenGL.Xamarin.OpenGL/files/.__override__/libmonosgen-2.0.so

```

**Comment by prepare** [comment]
from https://blogs.msdn.microsoft.com/visualstudioalm/2015/02/23/the-visual-studio-emulator-for-android-in-vs2015-ctp6/

>  ... the VS Emulator for Android can now render apps that make use of OpenGL ES up to version 2.0.  ....  (If you’re curious, **under the hood we’re forwarding OpenGL ES calls to the host machine’s GPU and using ANGLE to translate the calls to DirectX**).  

from ANGLE (https://chromium.googlesource.com/angle/angle/+/master/README.md)
 
still not fully support  GLES3.0 (in progress).

so It may cause the error on shader compilation on the emulator.

---
Do you mind if I convert it, to  make run on GLES2 ?

**Comment by zwcloud** [comment]
I see.

> Do you mind if I convert it, to make run on GLES2 ?
That's OK. Thank you!

**Comment by zwcloud** [comment]
Just got another response from a staff member of MS: The driver of the emulator hasn't supported OpenGLES 3.0. So currently the emulator won't support OpenGL ES 3.0 even if ANGLE does support.

**Comment by prepare** [comment]
I'm fixing the pull request.  The picture below is preview.


gles_android_emu
_pic 1: GLES2-based android demo, tess with C#  Tesselator, each glyph is rendered with glyph run's mesh_

**Comment by prepare** [comment]
This branch was merged.

But I change many things.
sorry for huge change.

:)

**Comment by zwcloud** [comment]
@prepare Thanks for the fix.
I just hope you can understand the way I use Typography and take that into consideration in further development.

**Comment by prepare** [comment]
I will implement you 'ITypographyTextContext' soon

**Comment by zwcloud** [comment]
**Just some thoughts here. I don't mean that Typography makes something wrong. No changes need to be done for main Typography project.**

The contours got from Typography seems to be in conflict with the rendering method used in this demo. I think the problem is caused by the following code:

```
case 1:
    {
        //we already have previous 1st control point (c1)
        //------------------------------------- 
        //please note that TrueType font
        //compose of Quadractic Bezier Curve (Curve3)
        //------------------------------------- 
        //in this case, this is NOT Cubic,
        //this is 2 CONNECTED Quadractic Bezier Curves
        //
        //we must create 'end point' of the first curve
        //and set it as 'begin point of the second curve.
        //
        //this is done by ...
        //1. calculate mid point between c1 and the latest point (p_x,p_y)
        Vector2 mid = GetMidPoint(c1, p_x, p_y);
        //2. generate curve3 ***
        tx.Curve3(c1.X, c1.Y, mid.X, mid.Y);
        //3. so curve control point number is reduce by 1
        curveControlPointCount--;
        //4. and set (p_x,p_y) as 1st control point for the new curve
        c1 = new Vector2(p_x, p_y);
        offCurveMode = true;
    }
```

Yes. The outlines of the characters (or glyphs) in TrueType fonts are made of straight line segments and quadratic Bézier curves. The code above add some indirection and erases a important information from a contour: **the winding order** (clockwise or anti-clockwise). But the rendering method used by my android demo needs to know that when transform `curve3` to the rendering data (I mean vertex buffer). 

I think I will write a reader and make the winding order available to `Curve3` callback.

I'll try to fix the existing demo when I have enough free time. 😄

**Comment by zwcloud** [comment]
Just finished implementing an optimized text rendering technique thanks to evanw's *Easy Scalable Text Rendering on the GPU*.

Preview:
result
msjh.ttf, font-size: 100

As I said, I'll try to fix the existing demo when I have enough free time.

**Comment by prepare** [comment]
Great!
please give me a time for reviewing process

**Pull request merged**
