### PR TITLE
Merge dev_for_latest_pixelfarm

### PR DESCRIPTION
**Pull request by zwcloud**
Request: keep the master branch up-to-date.

After this, first I will add and arrange documentation for Typography, then I will create a working example for Typography.TextFlow. And I hope you can guide me where and how to take text layout features back to this project.

### CODE REVIEW

**Comment by prepare** [comment]
@zwcloud , 

https://github.com/LayoutFarm/Typography/tree/dev_for_latest_pixelfarm 
is not ready to merge to main branch at this moment.

It may break other projects that use Typography,
so give me a time to check it.

But for PixelFarm latest dev,
Yes=> use  https://github.com/LayoutFarm/Typography/tree/dev_for_latest_pixelfarm

**Comment by zwcloud** [comment]
Understood.

**Comment by zwcloud** [comment]
👍 
It seems the latest code diverged a lot compared with the master branch. I hope your integration goes on smoothly.

**Comment by zwcloud** [comment]
Is it ready to be merged?

**Pull request merged**
