### PR TITLE
Promote GlyphPathBuilder in PixelFarm.Typography to Typography.OpenFont

### PR DESCRIPTION
**Pull request by Happypig375**
It nicely combines the TTF reader and CFF reader together, but somehow is not provided by default.

Also:
- Various formatting changes
- Made all projects buildable again (fixed all errors)
- Applied IDE fixes in lots of locations
- Renamed `HintTechnique` to `TrueTypeHintTechnique` because it is only used in the TTF reader
- Renamed `InvalidFontException` to `InvalidTrueTypeFontException` because it is only used in the TTF reader
- Moved `CharacterMap.cs` into the `Tables` folder because it is only used in `Cmap`, making it an internal class

### CODE REVIEW

**Comment by prepare** [comment]
please give me a time to test this

**Comment by prepare** [comment]
Thank you,
I accept your ideas
but  something can't be changed at this time.

(please wait,  I will stop old .net framework2.0 support,
and move to VS2019,  .netstandard and .netcore3.1 soon.
and then I will use some &lt;Span&gt; , read only struct etc)

---


GlyphPathBuilder was renamed to GlyphOutlineBuilder 
but it is not moved from PixelFarm.Typography to OpenFont.

because it may affect other libs that implement 
GlyphPathBuilderBase object.

- Various formatting changes
 => OK, 


- Made all projects buildable again (fixed all errors)
=> OK, Please test again after I edit it

- Applied IDE fixes in lots of locations
=> Please test again after I edit it

- Renamed `HintTechnique` to `TrueTypeHintTechnique` because it is only used in the TTF reader
=>  HintTechnique will be used in CFF too, CFF instruction hint will be implemented in the future.

- Renamed `InvalidFontException` to `InvalidTrueTypeFontException` because it is only used in the TTF reader
=> OK

- Moved `CharacterMap.cs` into the `Tables` folder because it is only used in `Cmap`, making it an internal class

=>OK


----

**Comment by Happypig375** [comment]
I only moved `GlyphPathBuilderBase` from `PixelFarm.Typography` to `GlyphPathBuilder` in `Typography.OpenFont`. The `GlyphOutlineBuilder` is the `GlyphPathBuilder` in `PixelFarm.Typography` but renamed to avoid name clashes leading to compiler errors.

>because it may affect other libs that implement
GlyphPathBuilderBase object.

The solution is a simple rename. This change is small enough. I don't understand the resistance to add a type unifying the TTF reader and the CFF reader to Typography.OpenFont. The existing `GlyphPathBuilderBase`'s placement does not make sense either. It is in `PixelFarm.Typography`'s "step 4", but its subclass extending it to make a `DynamicOutline` is placed in "step 1.1". This constitutes a circular reference and is already making readers confused. Moreover, the base class can stand on its own without referencing any other code in `PixelFarm.Typography`. This makes it an ideal candidate to promote to `Typography.OpenFont`. Also, moving it to `Typography.OpenFont` actually __simplifies__ the usage of Typography since currently the base class need to be referenced to ensure correct implementation of reading glyphs without differentiating TTF fonts from CFF fonts. As evidence, all demo projects reference it, so why is it not included in `Typography.OpenFont` by default?

**Comment by prepare** [comment]
**Typography.OpenFont** is about how to read/interpret the Font files
   so I don't add the code about How to Build outline/path to here.

  This still free the developer's mind about how to build the Glyph 
  from reading font data. 

   I agree that a GlyphOutlineBuilder code is useful,
    but it is just an example,
    not a standard,
    It can't live inside the core.

---
  
 Other devs may implement their own (Advanced) GlyphOutlineBuilder.  
    
  so I wrote this 

 >because it may affect other libs that implement
 GlyphPathBuilderBase object.

**Comment by Happypig375** [comment]
>Typography.OpenFont is about how to read/interpret the Font files
so I don't add the code about How to Build outline/path to here.

If that is the case, then `Typography.GlyphLayout`, judging by its name, will be a more suitable candidate to add this code into. 

>This still free the developer's mind about how to build the Glyph
from reading font data.

Adding a _correct_ implementation of glyph-drawing does not prohibit developers from reinventing the wheel, i.e. building a glyph by themselves.

>I agree that a GlyphOutlineBuilder code is useful,
but it is just an example,
not a standard,
It can't live inside the core.

I would define `GlyphPathBuilder` as a convenient way to omit the need to switch between the TTF glyph reader and the CFF glyph reader. It is not a standard, but it simplifies the usage of Typography.

>Other devs may implement their own (Advanced) GlyphOutlineBuilder.

Again, adding a class as a convenient shortcut does not prevent developers from using the TTF reader or the CFF reader directly. 

>so I wrote this

>>because it may affect other libs that implement
GlyphPathBuilderBase object.

Moving it to the code actually encourages adoption of this class. For existing libraries, it is just a simple rename of the base class. I see nothing wrong with this.

**Comment by prepare** [comment]
**Typography.GlyphLayout** is about layout glyphs( text-shaping engine)
with advanced OpenType/OpenFont features. 

On this layer, we see a glyph as a 'simple rectangle'.
and This layer dose not need to know about 'curves' of glyph.

By this concept, a GlyphOutlineBuilder is not placed here.

so I place a GlyphOutlineBuilder on an 'outer' layer of GlyphLayout.
eg. some graphics layer that we talk about curve, beziers etc.

core1_2


But this design may be changed in the future.

**Comment by prepare** [comment]
I admit that this look not convenient.

:)

**Comment by Happypig375** [comment]
By this definition, `Typography.OpenFont.IGlyphTranslator` should not exist in `Typography.OpenFont`. It directly exposes a graphics layer, directly contradicts this design.

**Comment by prepare** [comment]
IGlyphTranslator just read and
translate data (x,y, curve type (or move to, lineto))
from data in font file and
send to the user/listener of this class.

It knows and understands all curves but
it dose not create /hold any advance curves/graphics object.
(bezire segments/line segments/linejoins etc)
 
I think just x,y,curve type,color is OK at this layer.

**Comment by prepare** [comment]
I will create a new sub-project called Typography.One (Typography.One.dll)

It will combine source files (shared) from all
subprojects (OpenFont,GlyphLayout, TextBreak,TextFlow,TextServices)
together plus GlyphOutlineBuilder (+/- Altas)

This will be an all-in-one
convenient/ easy-to-use dll.

**Comment by Happypig375** [comment]
>IGlyphTranslator just read and
translate data (x,y, curve type (or move to, lineto))
from data in font file and
send to the user/listener of this class.

>It knows and understands all curves but
it dose not create /hold any advance curves/graphics object.
(bezire segments/line segments/linejoins etc)

So does `GlyphOutlineBuilder`. It merely stores point objects generated by the TTF and CFF readers.

**Pull request merged**
